application: bush-website
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(css|js|png))
  static_files: static/\1
  upload: static/(.*\.(css|js|png))

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
